### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by uN1K0Rn86** [kaltionkasvatti/magic-library#1]
Sovellus vaikuttaa toimivan enimmäkseen niin kuin on readme tiedostossa sanotaan. Kansiot -toiminto ei kuitenkaan ole käytössä. Etusivulla näkyy vain että kansioita on 0. Mistään ei pääse lisäämään kortteja kansioihin eikä kansio-sivulle pääse myöskään manuaalisesti (bad request error). (Huom. en pelaa mtg:tä enkä tiedä mikä kansioiden tarkoitus on, joten voi olla että olen vain ymmärtänyt toiminnon väärin).

SQL skeema vaikuttaa järkevältä sovelluksen toiminnan kannalta. Taulujen välillä voisi olla viittauksia sopivissa paikoissa (esim. userid REFERENCES users).

Ulkoasu on tällä hetkellä aika olematon. Sovelluksen käyttö olisi huomattavasti mielekkäämpää jos sitä vähän tuunaisi. Navigaatiopalkki myös puuttuu kokonaan. Esim. kortin lisäyssivulta ei pääse pois muuten kuin lisäämällä kortin tai manuaalisesti.

Sovelluksen toiminnot on pitkälti keskitetty routes tiedostoon. Sitä saisi selkeämmäksi siirtämällä esim. SQL hakuja niille sopiviin tiedostoihin funktioina ja käyttämään niitä sitten importtien kautta. Näin koodi olisi luettavampaa.

Sovelluksen idea on hyvä ja enimmäkseen toimiva. Lopuksi muutama huomio ja esiin tulleita virheitä:

- Kun korttia muokkaa siten että "power" ja "toughness" ovat tyhjiä ennen muokkaamista ja vain toiselle antaa arvon, tulee "internal server error". Jos tämä ei ole validi muokkaustapa, voisi tulla virheviesti joka kertoo miksi näin on.   invalid input syntax for type integer: ""
                LINE 7:                                 toughness='' 
                                                  ^

             [SQL: UPDATE cards SET name=%(cardname)s, 
                                twofaced=%(two_faced)s, 
                                colour=%(colours)s,
                                cmc=%(cmc)s, 
                                rarity=%(rarity)s, 
                                power=%(power)s, 
                                toughness=%(toughness)s 
                                WHERE id=%(card)s]
- Kortin muokkaus ei muutenkaan toimi. routes.py tiedoston funktiosta sendedit puuttuu return komento (rivi 221).  Rivillä 219 on myös turha debug print komento.
- Users.py tiedosto on importteja lukuun ottamatta tyhjä. Onko tarkoitus siirtää sinne toimintoja routes tiedostosta?

**Comment by kaltionkasvatti** [comment]
- Kansioita voi nyt lisätä ja poistaa
- Kortin editointi korjattu
- SQL-skeema päivitetty
- toimintoja ulkoistettu muille moduuleille
- /newcardilta voi nyt palata etusivulle
